// react-lazy/src/App.tsx
import {useState} from 'react'
import './App.css'
import {Toggle} from '@frlow/brine-example/wrapper/react/Toggle.lazy'

function App() {
  const [showToggle, setShowToggle] = useState(false)
  const [toggled, setToggled] = useState(false)

  return (
    <div style={{display: "flex", flexDirection: "column", gap: "2rem"}}>
      <div>Toggle button is lazy loaded when it is first rendered</div>
      <button onClick={() => setShowToggle(true)}>Show toggle</button>
      {showToggle && <Toggle checked={toggled} onChange={() => setToggled(!toggled)}/>}
    </div>
  )
}

export default App

// vue-simple/src/App.vue
<script setup lang="ts">
import Toggle from '@frlow/brine-example/wrapper/vue/Toggle.vue'
import {ref} from 'vue'

const toggled = ref(false)
const toggle = () => {
  toggled.value = !toggled.value
}
</script>

<template>
  <Toggle :checked="toggled" @change="()=>toggle()"></Toggle>
</template>

<style scoped>

</style>
